### ISSUE TITLE
Fix the project generation

### ISSUE THREAD

**Issue by pepibumur** [xcodeswift/sake#1]
## Context 🕵️‍♀️
When the project to edit the `Sakefile.swift` gets generated there are a couple of issues:
- `Sakefile.swift` is contained with a group with name `.`.
- The linking against `SakefileDescription` is not properly setup so the library cannot be imported.

## What 🌱
Fix both issues to allow developers edit their `Sakefile.swift` files using Xcode.

## Proposal 🎉
Fix it!

**Comment by pepibumur** [comment]
@rahul-malik quick question since you have more experience with linking and projects configuration. Do you know which build-settings flag should I use to link a `.dylib` library from another target?

**Comment by rahul-malik** [comment]
@pepibumur - I'm familiar with linking sdk dylibs which are usually declared as `-l` + "framework name". 
- For example `-lc++`. 
If the dylib starts with `lib` you should remove that.
- `-llibc++` should just be `-lc++`

**Comment by pepibumur** [comment]
Thanks, @rahul-malik, it seems that the `-l` flag works. In the Swift Package Manage project they pass the argument as a Swift flag:

![image](https://user-images.githubusercontent.com/663605/33328022-301bbc5e-d459-11e7-822b-a97804c2c655.png)

However, I get this error. It looks like the architectures don't match and it's not able to read find the symbols:

![image](https://user-images.githubusercontent.com/663605/33328094-64d9a83e-d459-11e7-92e8-6aadfac45951.png)

**Comment by rahul-malik** [comment]
@pepibumur - Can you run `lipo` on your framework to see which architecture slices are available?

Example:
```
➜  iOS git:(master) lipo -info MyFramework.framework/MyFramework
Architectures in the fat file: MyFramework.framework/MyFramework are: i386 armv7 x86_64 arm64
```

**Comment by pepibumur** [comment]
This is what I get @rahul-malik:

```bash
# lipo -info .build/debug/libSakefileDescription.dylib
Non-fat file: .build/debug/libSakefileDescription.dylib is architecture: x86_64
```

**Comment by rahul-malik** [comment]
Looks like the architecture isnt the problem, it's just the dylib itself is not linked correctly so it thinks the symbols don't exist

**Comment by rahul-malik** [comment]
You might need to update the dylib search paths to contain the directory where the dylib is located in addition to the -l flag with the dylib name. 

http://lessons.livecode.com/m/4071/l/15029-linking-an-osx-external-bundle-with-a-dylib-library
