### ISSUE TITLE
Add auto-correct for `Sake` targets

### ISSUE THREAD

**Issue by rahul-malik** [xcodeswift/sake#25]
## Context 🕵️‍♀️
It's common that as you're running commands that you'll misspell the target name. If it's close enough to a known target name it would be great to either prompt or run that target automatically.

## What 🌱
If the target you are trying to run is close enough to a known target name, we should prompt the user or run that target automatically.

## Proposal 🎉
I imagine we can easily implement this by adding an implementation of the Levenshtein distance algorithm: https://en.wikipedia.org/wiki/Levenshtein_distance

If you're not familiar with the algorithm, it calculates the minimum number of edits (updates, deletes, inserts) to change one word into another. If the target name entered is within 2-3 edits of a known target we should prompt or run that target.

**Comment by pepibumur** [comment]
Great idea 😛. There are actually [some implementations](https://gist.github.com/bgreenlee/52d93a1d8fa1b8c1f38b) of that algorithm in Swift.
