### ISSUE TITLE
Dependencies in Sakefile

### ISSUE THREAD

**Issue by zdenektopic** [xcodeswift/sake#27]
## Context 🕵️‍♀️
It would be great to be able somehow use frameworks/libraries in the Sakefile.

## What 🌱
Lets say I would like to read some information from xcproj file. It would be great to have https://github.com/xcodeswift/xcproj available.

## Proposal 🎉
Add ability to use 3rd party libraries and frameworks.

**Comment by pepibumur** [comment]
That's a good idea @zdenektopic. Without thinking about technical details, how do you think the API should be to define these dependencies?

**Comment by reeichert** [comment]
Without thinking about technical details, maybe inline dependency, as seen in [Marathon](https://github.com/JohnSundell/Marathon#specifying-dependencies-inline)

**Comment by pepibumur** [comment]
I see. I was thinking about something similar, using comments in the `Sakefile.swift`. What about

```swift
// Sakefile.swift

// dependency: https://github.com/xcodeswift/xcproj.git
// dependency: https://github.com/yonaskolb/XcodeGen.git

// Your Sake tasks definition.
```

**Comment by pepibumur** [comment]
Hey @reeichert & @zdenektopic I've moved this issue to an Epic https://github.com/xcodeswift/sake/issues/34. I recommend you to install [Zenhub](https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd) to properly see the epic and all the issues that belong to it. 
I've also created some issues to work on this epic. Feel free to pick up any that you'd be interested in contributing to.
