### ISSUE TITLE
Dependencies support

### ISSUE THREAD

**Issue by pepibumur** [xcodeswift/sake#34]
## Context 🕵️‍♀️
As @zdenektopic suggested on this issue https://github.com/xcodeswift/sake/issues/27. Support specifying dependencies from the Sakefile.

## Proposal 🎉
Developer could define dependencies using comments in the Sakefile file:

```swift
// Sakefile.swift

// dependency: https://github.com/xcodeswift/xcproj.git
// dependency: https://github.com/yonaskolb/XcodeGen.git

// Your Sake tasks definition.
```

**Comment by zdenektopic** [comment]
Would not be possible to employ SPM somehow? Otherwise I am fine having it Marathon-like.

**Comment by pepibumur** [comment]
I don't think so because then you'd need to split your Sake definition between the `Sakefile.swift` and a `Package.swift` in the same directory.

**Comment by zdenektopic** [comment]
Makes sense, ok.

**Comment by rahul-malik** [comment]
Can we bring in Swift PM as a framework here to use their dependency loading code or is that a bit much?

**Comment by pepibumur** [comment]
I think we could but we'd need to depend on SPM to parse the dependencies and generate the targets that we can link from `Sake`.  Not sure if maintaining that dependency will be easy but we can groom it a little bit and check if it's feasible. 

The other idea that I had in mind to add support for dependencies was defining them in the `Sakefile.swift` but without comments:

```swift
// Sakefile.swift

let dependencies = Dependencies(
  .dependency("https://github.com/xcodeswift/xcproj", .revision("xxx"))
)

Sake {
  $0.task(.build) {
    // Build task
  }
}
```

What do you think?

**Comment by pepibumur** [comment]
We could share efforts with XcodeGen where there are also plans to use SPM as a dependency management tool https://github.com/yonaskolb/XcodeGen/issues/196
