### ISSUE TITLE
Indefinite running

### ISSUE THREAD

**Issue by zdenektopic** [xcodeswift/sake#35]
## Context 🕵️‍♀️
Sometimes during development there is a need for tools like Sourcery and SwiftGen that have ability to be ran as "watchers" that regenerate some stuff when code changes.

## What 🌱
It would be great to have ability to have indefinite tasks in sake and also have clear guideline how to run multiple indefinite shell commands from single task.

## Proposal 🎉
Have completion callback for tasks:
```swift
Sake<Task> {
  try $0.task(.build) { (utils, completion) in
    // Here is where you define your build task
    completion() // task completed
  }
}.run()
```
and also indefinite shell runs with ability to kill them:
```swift
Sake<Task> {
  try $0.task(.build) { (utils, completion) in
    let killable = utils.shell.execute("sourcery --watch") // killable non-blocking
    killable.kill() // kill it
    completion() // task completed
  }
}.run()
```

**Comment by pepibumur** [comment]
Hey @zdenektopic. I'm not sure if that should be part of the Sake's scope. As far as I know, Rake or Make don't have such thing. Something like that could be achieved by using [Watchman](https://facebook.github.io/watchman/) from Facebook that would trigger a Sake command whenever any file changed. What do you think?

**Comment by pepibumur** [comment]
I'm closing the issue, because IMO this feature is not in the scope of Sake. If you feel like it's please, don't hesitate to write back on the issue and we can resume the discussion.
