### ISSUE TITLE
SIGINT signal not stopping child processes

### ISSUE THREAD

**Issue by dcordero** [xcodeswift/sake#40]
## Context 🕵️‍♀️
While using utils.shell, I found that when stoping `sake` with Ctrl + C, the subsequent steps are anyway executed.

## What 🌱
When sending SIGINT to sake via Control + C the child processes are not stoping with it. 

## Proposal 🎉
Not sure where exactly might be the problem. There might be some missing signal treatment to capture SIGINT to terminate the running Processes.

I am leaving here a few links, that found in a quick investigation, which could be useful for debugging:

- http://www.cocoabuilder.com/archive/cocoa/232336-ensure-nstask-terminates-when-parent-application-does.html
- http://alejandromp.com/blog/2016/5/29/swift-catch-os-signals-trap/
- https://github.com/IBM-Swift/BlueSignals

## Log
<img width="668" alt="screen shot 2017-12-21 at 00 51 06" src="https://user-images.githubusercontent.com/2320840/34266695-6e6af4ce-e67a-11e7-9edf-ccf46c6e7c95.png">

**Comment by pepibumur** [comment]
Good catch @dcordero and thanks for doing the research. We'll need to somehow propagate the stop action to any shell process initiated by Sake.

**Comment by pepibumur** [comment]
This should be solved now in master @dcordero
