### ISSUE TITLE
Feedback for result of generate-xcodeproj

### ISSUE THREAD

**Issue by dcordero** [xcodeswift/sake#47]
## Context 🕵️‍♀️
Executing `sake generate-xcodeproj` does not provide feedback of the result.

## What 🌱

Result of running generate-xcodeproj of spm:
```
$ swift package generate-xcodeproj
generated: ./sake.xcodeproj
$
```

Result of running `sake init`
```
$ sake init
Sakefile.swift generated
$
```

Result of running `sake generate-xcodeproj`
```
$ sake generate-xcodeproj
$
```

## Proposal 🎉
Adding a trace to `generate-xcodeproj` to provide some feedback.

**Comment by pepibumur** [comment]
Nice idea @dcordero. I've added the feedback on [this PR](https://github.com/xcodeswift/sake/pull/48)
