### ISSUE TITLE
Support keyboard input

### ISSUE THREAD

**Issue by pepibumur** [xcodeswift/sake#52]
## Context 🕵️‍♀️
If a command executed using `Utils.shell` prompts the user for some data the process doesn't take the data introduced by the keyboard.

## What 🌱
Update `Shell` to support keyboard inputs.

**Comment by Juanpe** [comment]
Any news about this?

**Comment by pepibumur** [comment]
Not really, I haven't had enough time to work on this. Would you like to take this over @Juanpe ?

**Comment by Juanpe** [comment]
Mmm...I tried to do it few weeks ago and I couldn't do it, but I could try again 💪

**Comment by pepibumur** [comment]
If you can it'd be great. I'll try to find time next week to help you with debugging.
