### ISSUE TITLE
Purpose of sake, new utils

### ISSUE THREAD

**Issue by olejnjak** [xcodeswift/sake#56]
## Context 🕵️‍♀️
I like the idea of `sake`. Right now I'm using `fastlane` on my projects and on projects at work. What I don't like is that I consider the whole fastlane ecosystem fragile so I hope that `sake` could be a bit more stable.

## What 🌱
I'd like to discuss the desired/expected purpose of sake. I'd appreciate something robust to simplify my CI/CD process. 

Ordinal process with `fastlane` looks like this:
1. set correct version of Xcode using `xcversion`
2. resolve provisioning using `match`
3. resolve dependencies using `carthage` or `cocoapods`
4. (in case of beta build) add beta badges to app icon using `badge` plugin in
5. run tests using `scan`
6. build app using `gym`
7. distribute build (HockeyApp/Testflight/etc.)

## Proposal 🎉
So the idea would be to add another utils which could simplify such process. I am not sure about all the mentioned tools but right now I think that util which would simplify using `xcodebuild` might be useful.

I'm open to contributing with such tool, but you know, I don't want to start with something that is not going to be useful.

What do you think? 🙂

**Comment by olbrichj** [comment]
To me this sounds great. I don't know wether it should be part of sake itself, as the focus would kinda drift away, but having these tools based on sake would be possible.

The only wish I'd have is supporting cocoa apps, as fastlane doesn't really do that.

**Comment by olejnjak** [comment]
Well, we might try to create a list of such tools, which might be useful to be part of sake itself and will also correspond with its purpose.

For now I think that creating an utility which will wrap the most common `xcodebuild` calls would be nice first step. What do you think?

**Comment by olbrichj** [comment]
The more I think about it, the more I come to the conclusion, that these tools should be in a separate repository. `make` is also not IDE/language specific.
Which shouldn't stop us ;)

My suggestion:
Let's create a separate repository and add all different kind of tools, starting with the most used `xcodebuild` calls. If we reach some maturity there, we could reconsider merging it with sake. What's your opinion?

**Comment by olejnjak** [comment]
Yep sounds good

**Comment by olbrichj** [comment]
will you create a repo or shall I

**Comment by olejnjak** [comment]
That would be nice :-)

**Comment by olbrichj** [comment]
Let's work here for now: https://github.com/olbrichj/Futsushu and continue our discussion in the tickets there.

we can move and rename it later on, but that shouldn't stop us.
Shall we close this?

**Comment by olejnjak** [comment]
Yep
